import 'package:flutter/material.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedInfoKesehatanWidget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedEllipse1Widget4.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedSpesialisKulitSpesialisMataSpesialisGigiSpesialisAnakSp.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedRectangle33Widget4.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedRectangle31Widget2.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedFrame4Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedTanyakanPadaWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid7widget/generated/GeneratedPolygon1Widget4.dart';

/* Frame Android - 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget4(),
              ),
              Positioned(
                left: 31.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 4.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 267.0,
                top: 344.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 4.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 100.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 30.0,
                child: GeneratedInfoKesehatanWidget1(),
              ),
              Positioned(
                left: 3.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 37.0,
                child: GeneratedRectangle31Widget2(),
              ),
              Positioned(
                left: 308.091552734375,
                top: 631.065185546875,
                right: null,
                bottom: null,
                width: 28.0,
                height: 20.0,
                child: GeneratedPolygon1Widget4(),
              ),
              Positioned(
                left: 167.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedEllipse1Widget4(),
              ),
              Positioned(
                left: 38.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 16.0,
                child: GeneratedRectangle33Widget4(),
              ),
              Positioned(
                left: 31.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 164.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 50.0,
                top: 413.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 134.0,
                child:
                    GeneratedSpesialisKulitSpesialisMataSpesialisGigiSpesialisAnakSp(),
              ),
              Positioned(
                left: 25.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 20.0,
                child: GeneratedTanyakanPadaWidget(),
              ),
              Positioned(
                left: 5.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 40.0,
                child: GeneratedFrame4Widget(),
              )
            ]),
      ),
    ));
  }
}
