import 'package:flutter/material.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedFrame6Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedEllipse1Widget7.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedRectangle3Widget3.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedLine2Widget3.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedRectangle1Widget7.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedKirimWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedRectangle33Widget7.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedFrame4Widget3.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedLiveChatWidget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedLine1Widget3.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedMasukkanKeluhanAndaWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedRectangle36Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedGgg1Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid6widget/generated/GeneratedPolygon1Widget7.dart';

/* Frame Android - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget7(),
              ),
              Positioned(
                left: 31.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 4.0,
                child: GeneratedLine1Widget3(),
              ),
              Positioned(
                left: 112.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 4.0,
                child: GeneratedLine2Widget3(),
              ),
              Positioned(
                left: 113.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 30.0,
                child: GeneratedLiveChatWidget1(),
              ),
              Positioned(
                left: 25.0,
                top: 372.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 20.0,
                child: GeneratedMasukkanKeluhanAndaWidget(),
              ),
              Positioned(
                left: 360.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 458.0,
                height: 157.0,
                child: GeneratedGgg1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 39.0,
                child: GeneratedRectangle32Widget(),
              ),
              Positioned(
                left: 308.091552734375,
                top: 634.065185546875,
                right: null,
                bottom: null,
                width: 28.0,
                height: 20.0,
                child: GeneratedPolygon1Widget7(),
              ),
              Positioned(
                left: 167.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedEllipse1Widget7(),
              ),
              Positioned(
                left: 38.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 16.0,
                child: GeneratedRectangle33Widget7(),
              ),
              Positioned(
                left: 234.0,
                top: 559.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 40.0,
                child: GeneratedFrame3Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 558.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 40.0,
                child: GeneratedFrame4Widget3(),
              ),
              Positioned(
                left: 43.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 204.0,
                child: GeneratedRectangle3Widget3(),
              ),
              Positioned(
                left: 54.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 108.0,
                child: GeneratedFrame6Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 405.0,
                right: null,
                bottom: null,
                width: 253.0,
                height: 132.0,
                child: GeneratedRectangle36Widget(),
              ),
              Positioned(
                left: 254.0,
                top: 517.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 23.0,
                child: GeneratedKirimWidget(),
              )
            ]),
      ),
    ));
  }
}
