import 'package:flutter/material.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedMasukdenganGoogleWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedMASUKWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedTeleponatauemailWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedKelompok8unpakacidWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedPolygon1Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedLupaPasswordWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid4widget/generated/GeneratedPasswordWidget.dart';

/* Frame Android - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 1.0,
                top: -19.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 146.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 66.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 42.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 30.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 170.0,
                right: null,
                bottom: null,
                width: 227.0,
                height: 18.0,
                child: GeneratedTeleponatauemailWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 52.0,
                child: GeneratedRectangle16Widget(),
              ),
              Positioned(
                left: 119.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 43.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 62.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 251.0,
                height: 33.0,
                child: GeneratedMASUKWidget(),
              ),
              Positioned(
                left: 121.0,
                top: 460.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 27.0,
                child: GeneratedLupaPasswordWidget(),
              ),
              Positioned(
                left: 24.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 42.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 93.0,
                top: 516.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 21.0,
                child: GeneratedMasukdenganGoogleWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 507.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 34.0,
                child: GeneratedRectangle21Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 39.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 1.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 39.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 287.09149169921875,
                top: 634.065185546875,
                right: null,
                bottom: null,
                width: 28.0,
                height: 20.0,
                child: GeneratedPolygon1Widget(),
              ),
              Positioned(
                left: 156.0,
                top: 606.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 16.0,
                child: GeneratedRectangle33Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 53.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 35.0,
                child: GeneratedKelompok8unpakacidWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 36.0,
                child: GeneratedWidget(),
              )
            ]),
      ),
    ));
  }
}
