import 'package:flutter/material.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid10widget/generated/GeneratedEllipse1Widget6.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid10widget/generated/GeneratedFrame4Widget2.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid10widget/generated/GeneratedKpdDrSpesialisMataPakmatasayaselaluberairdanmemerahseti.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid10widget/generated/GeneratedRectangle31Widget4.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid10widget/generated/GeneratedLine2Widget2.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid10widget/generated/GeneratedLine1Widget2.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid10widget/generated/GeneratedKeluhanAndaTerkirimWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid10widget/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid10widget/generated/GeneratedRectangle1Widget6.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid10widget/generated/GeneratedRectangle33Widget6.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid10widget/generated/GeneratedPolygon1Widget6.dart';

/* Frame Android - 10
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid10Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget6(),
              ),
              Positioned(
                left: 31.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 4.0,
                child: GeneratedLine2Widget2(),
              ),
              Positioned(
                left: 259.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 4.0,
                child: GeneratedLine1Widget2(),
              ),
              Positioned(
                left: 100.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 30.0,
                child: GeneratedKeluhanAndaTerkirimWidget(),
              ),
              Positioned(
                left: 3.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 37.0,
                child: GeneratedRectangle31Widget4(),
              ),
              Positioned(
                left: 308.091552734375,
                top: 631.065185546875,
                right: null,
                bottom: null,
                width: 28.0,
                height: 20.0,
                child: GeneratedPolygon1Widget6(),
              ),
              Positioned(
                left: 167.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedEllipse1Widget6(),
              ),
              Positioned(
                left: 38.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 16.0,
                child: GeneratedRectangle33Widget6(),
              ),
              Positioned(
                left: 5.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 40.0,
                child: GeneratedFrame4Widget2(),
              ),
              Positioned(
                left: 12.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 309.0,
                height: 191.0,
                child: GeneratedRectangle37Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 129.0,
                right: null,
                bottom: null,
                width: 299.0,
                height: 193.0,
                child:
                    GeneratedKpdDrSpesialisMataPakmatasayaselaluberairdanmemerahseti(),
              )
            ]),
      ),
    ));
  }
}
