import 'package:flutter/material.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedTambahkanWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedBersama85019065unpakacidWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedRectangle33Widget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedPolygon1Widget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedRectangle17Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedWidi085019010unpakacidWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedShintia085019032unpakacidWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedRere085019008unpakacidWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedMasukDenganWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid8widget/generated/GeneratedLine3Widget.dart';

/* Frame Android - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 61.0,
                child: GeneratedRectangle17Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 33.0,
                child: GeneratedWidi085019010unpakacidWidget(),
              ),
              Positioned(
                left: 50.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 61.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 61.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 50.0,
                top: 208.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 33.0,
                child: GeneratedRere085019008unpakacidWidget(),
              ),
              Positioned(
                left: 19.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 306.0,
                height: 61.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 33.0,
                child: GeneratedShintia085019032unpakacidWidget(),
              ),
              Positioned(
                left: -12.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 390.0,
                height: 43.0,
                child: GeneratedRectangle31Widget(),
              ),
              Positioned(
                left: 305.091552734375,
                top: 634.065185546875,
                right: null,
                bottom: null,
                width: 28.0,
                height: 20.0,
                child: GeneratedPolygon1Widget1(),
              ),
              Positioned(
                left: 180.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 38.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 16.0,
                child: GeneratedRectangle33Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 41.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 41.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 260.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 41.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 19.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 41.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 92.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 30.0,
                child: GeneratedMasukDenganWidget(),
              ),
              Positioned(
                left: 113.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 4.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 335.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 4.0,
                child: GeneratedLine3Widget1(),
              ),
              Positioned(
                left: 73.0,
                top: 375.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 33.0,
                child: GeneratedBersama85019065unpakacidWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 435.0,
                right: null,
                bottom: null,
                width: 309.0,
                height: 50.0,
                child: GeneratedTambahkanWidget(),
              )
            ]),
      ),
    ));
  }
}
