import 'package:flutter/material.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid9widget/generated/GeneratedRectangle1Widget5.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid9widget/generated/GeneratedLine2Widget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid9widget/generated/GeneratedRectangle31Widget3.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid9widget/generated/GeneratedLine1Widget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid9widget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid9widget/generated/GeneratedRectangle33Widget5.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid9widget/generated/GeneratedPolygon1Widget5.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid9widget/generated/GeneratedEllipse1Widget5.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid9widget/generated/GeneratedFrame4Widget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid9widget/generated/GeneratedJadwalSpesialisMataWidget.dart';

/* Frame Android - 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget5(),
              ),
              Positioned(
                left: 31.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 4.0,
                child: GeneratedLine2Widget1(),
              ),
              Positioned(
                left: 259.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 4.0,
                child: GeneratedLine1Widget1(),
              ),
              Positioned(
                left: 100.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 30.0,
                child: GeneratedJadwalSpesialisMataWidget(),
              ),
              Positioned(
                left: 3.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 37.0,
                child: GeneratedRectangle31Widget3(),
              ),
              Positioned(
                left: 308.091552734375,
                top: 631.065185546875,
                right: null,
                bottom: null,
                width: 28.0,
                height: 20.0,
                child: GeneratedPolygon1Widget5(),
              ),
              Positioned(
                left: 167.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedEllipse1Widget5(),
              ),
              Positioned(
                left: 38.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 16.0,
                child: GeneratedRectangle33Widget5(),
              ),
              Positioned(
                left: 31.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 407.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 5.0,
                top: 545.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 40.0,
                child: GeneratedFrame4Widget1(),
              )
            ]),
      ),
    ));
  }
}
