import 'package:flutter/material.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedEllipse1Widget2.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedInfoKesehatanWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedPolygon1Widget2.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedRectangle24Widget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedSELAMATDATANGWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedLogoutWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedRectangle31Widget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedLiveChatWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid5widget/generated/GeneratedRectangle33Widget2.dart';

/* Frame Android - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 31.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 204.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 457.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 29.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 57.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 29.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 548.0,
                right: null,
                bottom: null,
                width: 239.0,
                height: 29.0,
                child: GeneratedRectangle24Widget1(),
              ),
              Positioned(
                left: 5.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 47.0,
                child: GeneratedSELAMATDATANGWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 464.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 24.0,
                child: GeneratedLiveChatWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 24.0,
                child: GeneratedInfoKesehatanWidget(),
              ),
              Positioned(
                left: 61.0,
                top: 549.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 27.0,
                child: GeneratedLogoutWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 370.0,
                height: 43.0,
                child: GeneratedRectangle31Widget1(),
              ),
              Positioned(
                left: 287.09149169921875,
                top: 634.065185546875,
                right: null,
                bottom: null,
                width: 28.0,
                height: 20.0,
                child: GeneratedPolygon1Widget2(),
              ),
              Positioned(
                left: 161.0,
                top: 603.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedEllipse1Widget2(),
              ),
              Positioned(
                left: 38.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 16.0,
                child: GeneratedRectangle33Widget2(),
              )
            ]),
      ),
    ));
  }
}
