import 'package:flutter/material.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedRectangle33Widget3.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedPolygon1Widget3.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedEllipse1Widget3.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedDAFTARWidget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedMASUKWidget1.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/kelompok_206app/generatedandroid3widget/generated/GeneratedDOKTERKUWidget.dart';

/* Frame Android - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroid3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 640.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 126.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 59.0,
                child: GeneratedWidget1(),
              ),
              Positioned(
                left: 38.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 35.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 47.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 25.0,
                child: GeneratedMASUKWidget1(),
              ),
              Positioned(
                left: 201.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 102.0,
                height: 35.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 211.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 25.0,
                child: GeneratedDAFTARWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 39.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 287.09149169921875,
                top: 634.065185546875,
                right: null,
                bottom: null,
                width: 28.0,
                height: 20.0,
                child: GeneratedPolygon1Widget3(),
              ),
              Positioned(
                left: 161.0,
                top: 607.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 27.0,
                child: GeneratedEllipse1Widget3(),
              ),
              Positioned(
                left: 38.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 23.0,
                height: 16.0,
                child: GeneratedRectangle33Widget3(),
              ),
              Positioned(
                left: 17.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 290.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 9.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 50.0,
                child: GeneratedDOKTERKUWidget(),
              )
            ]),
      ),
    ));
  }
}
